
export const board = [ 'redPlate', 'redPlate', 'none', 'none', 'grass', 'grass', 'blueArea', 'none', 'none', 'bluePlate', 'bluePlate',
                'redPlate', 'redPlate', 'none', 'none', 'grass','blueFinish', 'grass', 'none', 'none', 'bluePlate', 'bluePlate',
                'none', 'none', 'none', 'none', 'grass', 'blueFinish', 'grass', 'none', 'none', 'none', 'none',
                'none', 'none', 'none', 'none', 'grass', 'blueFinish', 'grass', 'none', 'none', 'none', 'none',
                'redArea', 'grass', 'grass', 'grass', 'grass', 'blueFinish', 'grass', 'grass', 'grass', 'grass', 'grass',
                'grass', 'redFinish', 'redFinish', 'redFinish', 'redFinish', 'none', 'greenFinish', 'greenFinish', 'greenFinish', 'greenFinish', 'grass',
                'grass','grass','grass','grass','grass','yellowFinish', 'grass','grass','grass','grass', 'greenArea',
                'none', 'none', 'none', 'none', 'grass', 'yellowFinish', 'grass', 'none', 'none', 'none', 'none',
                'none', 'none', 'none', 'none', 'grass', 'yellowFinish', 'grass', 'none', 'none', 'none', 'none',
                'yellowPlate', 'yellowPlate', 'none', 'none', 'grass', 'yellowFinish', 'grass', 'none', 'none', 'greenPlate', 'greenPlate',
                'yellowPlate', 'yellowPlate', 'none', 'none', 'yellowArea', 'grass', 'grass', 'none', 'none', 'greenPlate', 'greenPlate',
            ]

            export const nboard = [
                {1: 'redPlate'},
                {2: 'redPlate'},
                {0: 'none'},
                {0: 'none'},
                {5: 'grass'},
                {6: 'grass'},
                {7: 'blueArea'},
                {0: 'none'},
                {0: 'none'},
                {10: 'bluePlate'},
                {11: 'bluePlate'},
                {12: 'redPlate'},
                {13: 'redPlate'},
                {0: 'none'},
                {0: 'none'},
                {16: 'grass'},
                {17: 'blueFinish'},
                {18: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {21: 'bluePlate'},
                {22: 'bluePlate'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {27: 'grass'},
                {28: 'blueFinish'},
                {29: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {36: 'grass'},
                {37: 'blueFinish'},
                {38: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {43: 'redArea'},
                {44: 'grass'},
                {45: 'grass'},
                {46: 'grass'},
                {47: 'grass'},
                {48: 'blueFinish'},
                {49: 'grass'},
                {50: 'grass'},
                {51: 'grass'},
                {52: 'grass'},
                {53: 'grass'},
                {54: 'grass'},
                {55: 'redFinish'},
                {56: 'redFinish'},
                {57: 'redFinish'},
                {58: 'redFinish'},
                {0: 'none'},
                {60: 'greenFinish'},
                {61: 'greenFinish'},
                {62: 'greenFinish'},
                {63: 'greenFinish'},
                {64: 'grass'},
                {65: 'grass'},
                {66: 'grass'},
                {67: 'grass'},
                {68: 'grass'},
                {69: 'grass'},
                {70: 'yellowFinish'},
                {71: 'grass'},
                {72: 'grass'},
                {73: 'grass'},
                {74: 'grass'},
                {75: 'greenArea'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {80: 'grass'},
                {81: 'yellowFinish'},
                {82: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {91: 'grass'},
                {92: 'yellowFinish'},
                {93: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {0: 'none'},
                {98: 'yellowPlate'},
                {99: 'yellowPlate'},
                {0: 'none'},
                {0: 'none'},
                {102: 'grass'},
                {103: 'yellowFinish'},
                {104: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {107: 'greenPlate'},
                {108: 'greenPlate'},
                {109: 'yellowPlate'},
                {110: 'yellowPlate'},
                {0: 'none'},
                {0: 'none'},
                {113: 'yellowArea'},
                {114: 'grass'},
                {115: 'grass'},
                {0: 'none'},
                {0: 'none'},
                {118: 'greenPlate'},
                {119: 'greenPlate'},
            ];

